### ISSUE TITLE
Some analog inputs

### ISSUE THREAD

**Issue by rusefillc** [rusefi/S105#3]
а можно MAF/CLT/IAT/MAP

**Comment by Nadezhda-n** [comment]
![image](https://user-images.githubusercontent.com/99179773/217914748-9c120c37-a33d-4e9a-864f-6826c924eb83.png)

**Comment by rusefillc** [comment]
@Nadezhda-n glitch?

![image](https://user-images.githubusercontent.com/48498823/217917279-45aa590b-ed24-41c9-9aa4-e733a0aab362.png)
